import json, collections, re
rows=[json.loads(l) for l in open("paper/writing/data/campaign_summary.jsonl")]
def parse(n):
    m=re.match(r"lrsw_(.+)_lr([0-9a-z]+)_s42$", n)
    return (m.group(1),m.group(2)) if m else None
best={}
for r in rows:
    n=r["run_name"]
    if not n.startswith("lrsw_") or not parse(n): continue
    if n not in best or r["evaluated_at"]>best[n]["evaluated_at"]: best[n]=r
lrorder=["2e5","5e5","1e4","2e4","3e4","5e4","1e3"]
LRTEX={"2e5":r"2\!\times\!10^{-5}","5e5":r"5\!\times\!10^{-5}","1e4":r"1\!\times\!10^{-4}",
       "2e4":r"2\!\times\!10^{-4}","3e4":r"3\!\times\!10^{-4}","5e4":r"5\!\times\!10^{-4}","1e3":r"1\!\times\!10^{-3}"}
cov=collections.defaultdict(dict)
for n,r in best.items():
    arm,lr=parse(n); ad=r.get("cs_avg"); ret=r.get("retention_mean")
    if ad is None or ret is None or r.get("fdelta",0)>50: continue
    cov[arm][lr]=dict(adapt=ad,ret=ret,lr=lr)
lora=cov["lora_r16"]; lorawd=cov["lorawd_wd0p3"]
def dominates(a,b): return a["adapt"]>=b["adapt"] and a["ret"]>=b["ret"] and (a["adapt"]>b["adapt"] or a["ret"]>b["ret"])
def pareto(pts): return sorted([p for p in pts if not any(dominates(q,p) for q in pts if q is not p)],key=lambda p:p["adapt"])
lorawd_fr=pareto([lorawd[l] for l in lrorder if l in lorawd])
lora_fr  =pareto([lora[l] for l in lrorder if l in lora])
comb_fr  =pareto([lorawd[l] for l in lrorder if l in lorawd]+[lora[l] for l in lrorder if l in lora])

fancy=["dora_r16","milora_r32","sclora_r32","lora_null_r16","clora_k1024","corda_r16"]
NAMES={"dora_r16":"DoRA","corda_r16":"CorDA","milora_r32":"MiLoRA","sclora_r32":"SC-LoRA","lora_null_r16":"LoRA-Null","clora_k1024":"CLoRA"}

def best_single(arm):
    m=cov[arm]
    cand=[m[l] for l in lrorder if l in m and m[l]["ret"]>=24.0] or [m[l] for l in lrorder if l in m]
    return max(cand,key=lambda p:p["adapt"])

def dom_pt(fr,pt):
    d=[p for p in fr if dominates(p,pt)]
    return max(d,key=lambda p:p["adapt"]+p["ret"]) if d else None

lines=[]
lines.append(r"% Auto-generated by make_table.py — LR-artifact exhibit (Claim 3). Llama-2, commonsense, seed 42.")
lines.append(r"\begin{table}[t]")
lines.append(r"\centering")
lines.append(r"\small")
lines.append(r"\setlength{\tabcolsep}{4pt}")
lines.append(r"\caption{\textbf{The ``win'' of every structured adapter is a learning-rate artifact.}")
lines.append(r"For each method we take its \emph{best-looking single learning rate} (the LR that maximises")
lines.append(r"commonsense adaptation while keeping retention $\ge 24$; if none clears it, the highest-adapt LR,")
lines.append(r"marked $\dagger$). At that fixed LR the method can beat plain LoRA \emph{run at the same LR}")
lines.append(r"(columns 2--4). But once the learning rate is \emph{swept}, LoRA+wd traces a Pareto frontier that")
lines.append(r"dominates the method's best single-LR point on \emph{both} axes (columns 5--6). Adapt = commonsense")
lines.append(r"accuracy; Ret = mean(BBH, MMLU-Pro). Llama-2-7B, seed 42, 7 LRs.}")
lines.append(r"\label{tab:lr_artifact}")
lines.append(r"\begin{tabular}{l cc c cc}")
lines.append(r"\toprule")
lines.append(r" & \multicolumn{3}{c}{\textbf{Single-LR view (fixed LR)}} & \multicolumn{2}{c}{\textbf{Swept view}} \\")
lines.append(r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}")
lines.append(r"Method & Method @ LR$^\star$ & LoRA @ same LR & $\Delta$adapt & Dominating LoRA+wd pt & Dominates? \\")
lines.append(r" & (adapt / ret) & (adapt / ret) & (pp) & (LR: adapt / ret) & \\")
lines.append(r"\midrule")

verdicts={}
for arm in fancy:
    bp=best_single(arm); lr=bp["lr"]
    lsame=lora.get(lr)
    dagger=r"$^\dagger$" if bp["ret"]<24.0 else ""
    wd=dom_pt(lorawd_fr,bp)
    lo=dom_pt(comb_fr,bp)
    dadapt = bp["adapt"]-lsame["adapt"] if lsame else float("nan")
    lsame_s = f"{lsame['adapt']:.1f} / {lsame['ret']:.1f}" if lsame else "--"
    if wd:
        wd_s=f"${LRTEX[wd['lr']]}$: {wd['adapt']:.1f} / {wd['ret']:.1f}"
        dom_s=r"\textbf{yes}"
    else:
        wd_s="-- (incomparable)"; dom_s="no"
    verdicts[arm]=dict(bp=bp,lr=lr,lsame=lsame,wd=wd,lo=lo,dadapt=dadapt)
    lines.append(f"{NAMES[arm]} & {bp['adapt']:.1f} / {bp['ret']:.1f}{dagger} (${LRTEX[lr]}$) & {lsame_s} & {dadapt:+.1f} & {wd_s} & {dom_s} \\\\")

lines.append(r"\bottomrule")
lines.append(r"\end{tabular}")
lines.append(r"\end{table}")

out="paper/writing/tables/table_lr_artifact.tex"
open(out,"w").write("\n".join(lines)+"\n")
print("wrote",out)
print("\n--- verdicts ---")
for arm,v in verdicts.items():
    print(NAMES[arm], "lr",v["lr"], "bp",round(v["bp"]["adapt"],1),round(v["bp"]["ret"],1),
          "| dadapt vs LoRA@sameLR", round(v["dadapt"],1),
          "| LoRA+wd dom:", (v["wd"]["lr"],round(v["wd"]["adapt"],1),round(v["wd"]["ret"],1)) if v["wd"] else None)
print("\nLoRA+wd frontier:",[(p["lr"],round(p["adapt"],1),round(p["ret"],1)) for p in lorawd_fr])
