"""Reconstruct inline manuscript tables/figure from archived CSVs (no training).

Run --check to verify checked-in rows; --write to regenerate them.
--patch emits an apply_patch change for the same deterministic outputs.
"""
from pathlib import Path
import argparse
import csv
from collections import defaultdict
from statistics import mean, stdev
import re
from decimal import Decimal
from analyze_archived_layers import latex as block_latex, analyze

ROOT = Path(__file__).resolve().parents[1]
TASKS = [('rte_lin', 'RTE'), ('mrpc_lin', 'MRPC'), ('cola_lin', 'CoLA'),
         ('stsb_lin', 'STS-B'), ('sst2_lin', 'SST-2')]
CONDS = [('A_no_reg', 'A'), ('B_muE_only', 'B'), ('C_muE_nuD', 'C')]

def normalize_task(task):
    return task.replace('sts-b', 'stsb').replace('sts_b', 'stsb')

def reconstruct():
    _, _, allocations = analyze(include_runs=True)
    grouped = defaultdict(list)
    seen = set()
    for path in sorted((ROOT / 'data' / 'legacy_mixing').glob('*.csv')):
        with path.open(newline='') as handle:
            for row in csv.DictReader(handle):
                # The earliest RTE export used an accuracy-specific column name.
                if 'final_val_score' not in row:
                    assert row['task'] == 'rte_lin' and 'final_val_accuracy' in row
                    row['final_val_score'] = row['final_val_accuracy']
                condition = next((key for key, _ in CONDS if row['run_name'].startswith(key)), None)
                if condition is None:
                    raise ValueError(f'Unexpected condition in {path}: {row["run_name"]}')
                task = normalize_task(row['task'])
                key = task, condition, int(row['seed'])
                if key in seen:
                    raise ValueError(f'Duplicate replicate: {key}')
                seen.add(key)
                grouped[task, condition].append(row)
    assert len(seen) == 27, f'Expected 27 archived rows, got {len(seen)}'
    def uncertainty(values, digits):
        if len(values) == 1:
            return f'${values[0]:.{digits}f}$'
        return f'${mean(values):.{digits}f} \\pm {stdev(values):.{digits}f}$'
    summary, full, costs = [], [], []
    for task, label in TASKS:
        seed_sets = [{int(r['seed']) for r in grouped[task, c]} for c, _ in CONDS]
        assert seed_sets[0] == seed_sets[1] == seed_sets[2]
        assert seed_sets[0] == ({42} if task == 'sst2_lin' else {42, 17})
        n = len(seed_sets[0])
        for condition, short in CONDS:
            cells = [label, short, str(n)]
            for field, digits, multiplier in [('final_val_score', 2, 100), ('mean_RelPert_F', 4, 1)]:
                cells.append(uncertainty([multiplier*float(r[field]) for r in grouped[task, condition]], digits))
            cells.append(uncertainty([100*allocations[task, condition, int(r['seed'])]['pCross']
                                      for r in grouped[task, condition]], 2))
            summary.append(' & '.join(cells) + r' \\')
            for record in sorted(grouped[task, condition], key=lambda r: int(r['seed'])):
                cells = [label, short, record['seed'], record['best_checkpoint_step']]
                for field, digits in [('final_val_score', 4), ('mean_mu_E', 3), ('mean_nu_D', 3),
                                      ('mean_RelPert_F', 3), ('mean_OffTailRatio_F', 3),
                                      ('mean_Drift_U', 3), ('mean_Drift_V', 3)]:
                    cells.append(f'{float(record[field]):.{digits}f}')
                full.append(' & '.join(cells) + r' \\')
                costs.append(' & '.join([label, short, record['seed'],
                                        f'{float(record["total_train_time"])/60:.2f}',
                                        f'{float(record["peak_gpu_memory"])/2**30:.3f}']) + r' \\')
        if task != TASKS[-1][0]:
            summary.append(r'\midrule')
            full.append(r'\midrule')
            costs.append(r'\midrule')
    prefix = '% Generated by scripts/build_mixing_tables.py from data/legacy_mixing/*.csv.\n'
    return {'MIXING SUMMARY': prefix + '\n'.join(summary) + '\n',
            'MIXING FULL': prefix + '\n'.join(full) + '\n',
            'ARCHIVED COST': prefix + '\n'.join(costs) + '\n'}

def glue_rows():
    with (ROOT / 'data/glue_reported.csv').open(newline='') as handle:
        records = list(csv.DictReader(handle))
    assert len(records) == 10
    rows = []
    for backbone in ('base', 'large'):
        if rows:
            rows.append(r'\midrule')
        rows.extend([r'\multicolumn{8}{c}{RoBERTa-' + backbone + r'} \\', r'\midrule',
                     r'\multicolumn{8}{l}{\textit{Imported reference runs (RandLoRA protocol; five runs)}} \\'])
        for record in [r for r in records if r['backbone'] == backbone]:
            if record['method'] == 'UIOrthoLoRA':
                rows.extend([r'\addlinespace', r'\multicolumn{8}{l}{\textit{Spectral instruments (reported protocol; six seeds)}} \\'])
            assert record['mrpc_metric'] == 'accuracy'
            cells = [record['method']]
            for task in ('sst2', 'mrpc', 'cola', 'qnli', 'rte', 'stsb'):
                cell = record[task + '_mean'] + r'{\scriptsize$\pm$' + record[task + '_sd'] + '}'
                cells.append(cell)
            avg6 = sum(Decimal(record[t + '_mean']) for t in ('sst2', 'mrpc', 'cola', 'qnli', 'rte', 'stsb')) / 6
            cells.append(f'{avg6:.2f}')
            rows.append(' & '.join(cells) + r' \\')
    return '\n'.join(rows) + '\n'

def manuscript_output():
    outputs = reconstruct()
    outputs.update(block_latex())
    outputs['GLUE ROWS'] = glue_rows()
    path = ROOT / 'neurips_2026.tex'
    content = path.read_text()
    for label, replacement in outputs.items():
        start = f'% BEGIN GENERATED {label}\n'
        end = f'% END GENERATED {label}'
        pattern = re.compile(re.escape(start) + r'.*?' + re.escape(end), re.S)
        assert len(pattern.findall(content)) == 1, f'Missing/duplicate region: {label}'
        content = pattern.sub(lambda _: start + replacement + end, content)
    return path, content

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--patch', action='store_true')
    args = parser.parse_args()
    path, content = manuscript_output()
    if args.check:
        assert path.read_text() == content, 'Stale or edited generated manuscript region; inspect --patch.'
        print('PASS: six inline regions reproduce from 27 summaries, 1,296 module records, and 10 GLUE rows.')
    elif args.write:
        path.write_text(content)
    else:
        print('*** Begin Patch')
        print(f'*** Update File: {path}\n@@')
        for line in path.read_text().splitlines():
            print('-' + line)
        for line in content.splitlines():
            print('+' + line)
        print('*** End Patch')

if __name__ == '__main__':
    main()
