"""05 — Generate the appendix exhibits created by the 2026-07-30 compression
pass (PI cut list): the TOST equivalence table, the MDE table, and the
per-benchmark fragility-slope table; plus (2026-08-02, PI request) the full
26-comparison head-to-head battery table for its dedicated appendix section.
Pure formatting of already-verified CSVs; no statistics are computed here.

Inputs : tost_offsets.csv, power_notes.csv, head2head_corrected.csv (this
         dir), ../insights/benchmark_fragility.csv
Outputs: ../../tables/table_tost.tex, table_mde.tex, table_fragility.tex,
         table_head2head.tex
Run: /home/guyb/UIOrthoLoRA/.venv/bin/python 05_make_appendix_tables.py
"""
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
TABLES = os.path.abspath(os.path.join(HERE, "..", "..", "tables"))
INSIGHTS = os.path.abspath(os.path.join(HERE, "..", "insights"))

DISPLAY = {"clora": "CLoRA", "dora": "DoRA", "lora": "LoRA",
           "lora_null": "LoRA-Null", "lorawdr16": "LoRA+wd (r16)",
           "milora": "MiLoRA", "milorawd": "MiLoRA+wd", "pissa": "PiSSA",
           "sclora": "SC-LoRA"}
FAM = {"llama_cs": "Llama CS", "llama_math": "Llama math",
       "qwen_cs": "Qwen CS", "qwen_math": "Qwen math"}
BENCH = {"bbh": "BBH", "mmlu_pro": "MMLU-Pro", "mmlu": "MMLU",
         "arc_c": "ARC-C", "truthfulqa": "TruthfulQA"}
HDR = ("% AUTO-GENERATED by acl_analysis/rq1_stats/05_make_appendix_tables.py\n"
       "% from verified rq1_stats / insights CSVs. Do not hand-edit numbers.\n")


def yn(v):
    return "yes" if v else "no"


def make_tost():
    t = pd.read_csv(os.path.join(HERE, "tost_offsets.csv"))
    p = t[t.scope.str.startswith("pooled")].sort_values("method")
    rows = []
    for _, x in p.iterrows():
        rows.append(f"  {DISPLAY[x.method]} & {int(x.n)} & {x.beta:+.2f} & "
                    f"$[{x.lo90:+.2f}, {x.hi90:+.2f}]$ & {yn(x.equiv_1pp)} & "
                    f"{yn(x.equiv_2pp)} & {yn(x.equiv_3pp)} \\\\")
    body = "\n".join(rows)
    tex = HDR + r"""\begin{table}[t]
\centering
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\caption{\textbf{Equivalence to LoRA{+}wd at matched update magnitude
(TOST).} Pooled model: retention on $\log_{10}\dw$ and method dummies
(reference LoRA{+}wd) with family fixed effects; CR1 cluster-robust errors
at the recipe-cell level ($n{=}1034$, $G{=}343$ cells). A method is
equivalent at margin $m$ iff the $90\%$ CI of its offset lies inside
$(-m,+m)$. LoRA{+}wd (r16) and MiLoRA{+}wd are weight-decay arms of the
reference itself; MiLoRA{+}wd has $n{=}2$ runs. Per-family offsets:
\texttt{rq1\_stats/tost\_offsets.csv}.}
\label{tab:tost}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{l r r c c c c}
\toprule
Method & $n$ & Offset (pp) & $90\%$ CI & $\pm1$ & $\pm2$ & $\pm3$ \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}%
}
\end{table}
"""
    open(os.path.join(TABLES, "table_tost.tex"), "w").write(tex)


def make_mde():
    t = pd.read_csv(os.path.join(HERE, "power_notes.csv"))
    t = t.dropna(subset=["mde_pp"])
    rows = []
    for fam, g in t.groupby("family"):
        rows.append(f"  {FAM[fam]} & {g.cell_sd_ret.median():.2f} & "
                    f"{g.mde_pp.median():.1f} & {g.mde_pp.max():.1f} \\\\")
    body = "\n".join(rows)
    tex = HDR + r"""\begin{table}[t]
\centering
\footnotesize
\caption{\textbf{Minimum detectable retention effects of the head-to-head
design} (two-sided paired $t$, $\alpha{=}.05$, power $.8$, exact noncentral
computation) at the observed common seeds and the empirical SD of paired
per-seed deltas vs LoRA{+}wd. Cell SD = median within-cell retention SD
over that family's multi-seed cells. Per-comparison values:
\texttt{rq1\_stats/power\_notes.csv}.}
\label{tab:mde}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{l c c c}
\toprule
Setting & Cell SD & Median MDE (pp) & Max MDE (pp) \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}%
}
\end{table}
"""
    open(os.path.join(TABLES, "table_mde.tex"), "w").write(tex)


def make_fragility():
    t = pd.read_csv(os.path.join(INSIGHTS, "benchmark_fragility.csv"))
    t = t[~t.contaminated]
    rows = []
    for b in ["mmlu_pro", "bbh", "mmlu", "truthfulqa"]:
        g = t[t.bench == b]
        lo, hi = g.norm_slope.min(), g.norm_slope.max()
        rows.append(f"  {BENCH[b]} & {len(g)} & "
                    f"${lo:+.2f}$ to ${hi:+.2f}$ \\\\")
    body = "\n".join(rows)
    tex = HDR + r"""\begin{table}[t]
\centering
\footnotesize
\caption{\textbf{Per-benchmark fragility}: ceiling-normalized degradation
slope (fraction of base capability lost per decade of $\dw$), range over
the six run families. The ordering MMLU-Pro $>$ BBH $>$ MMLU $>$ TruthfulQA
is identical in all six (Kendall $W{=}1.000$); ARC-Challenge is excluded as
a fine-tuning task. Source: \texttt{insights/benchmark\_fragility.csv}.}
\label{tab:fragility}
\begin{tabular}{l c c}
\toprule
Benchmark & Families & Normalized slope range \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    open(os.path.join(TABLES, "table_fragility.tex"), "w").write(tex)


def make_head2head():
    import numpy as np
    t = pd.read_csv(os.path.join(HERE, "head2head_corrected.csv"),
                    dtype={"ref_cell": str, "method_cell": str})
    fam_order = ["llama_cs", "llama_math", "qwen_cs", "qwen_math"]

    def fp(v, bold_sig=False):
        if not np.isfinite(v):
            return "--"
        s = f"{v:.3f}" if v >= 0.001 else f"{v:.4f}"
        return rf"\textbf{{{s}}}" if bold_sig and v < 0.05 else s

    def ci(lo, hi):
        if not (np.isfinite(lo) and np.isfinite(hi)):
            return "--"
        return f"$[{lo:+.1f}, {hi:+.1f}]$"

    rows = []
    for fam in fam_order:
        g = t[t.family == fam]
        ref = g.iloc[0].ref_cell
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{8}{c}{\textbf{%s} (reference LoRA{+}wd at %s)} \\"
                    % (FAM[fam].replace("CS", "commonsense"), ref))
        rows.append(r"\midrule")
        for _, x in g.iterrows():
            n = x["mode"].replace("paired(n=", "").replace(")", "") \
                if x["mode"].startswith("paired") else "1v3"
            test = "paired" if x["mode"].startswith("paired") else "n.t."
            rows.append(
                f"  {x.method} ({x.method_cell}) & {n}/{test} & "
                f"${x.d_ret:+.2f}$ & {ci(x.lo_ret, x.hi_ret)} & "
                f"{fp(x.p_ret_holm_all, True)} & "
                f"${x.d_adapt:+.2f}$ & {ci(x.lo_adapt, x.hi_adapt)} & "
                f"{fp(x.p_adapt_holm_all, True)} \\\\")
    body = "\n".join(rows)
    tex = HDR + r"""\begin{table*}[t]
\centering
\footnotesize
\setlength{\tabcolsep}{4pt}
\caption{\textbf{The full head-to-head battery vs LoRA{+}wd}
(Appendix~\ref{app:head2head}): all $26$ method $\times$ setting
comparisons at best-adaptation operating points. $\Delta$ = method $-$
LoRA{+}wd in points (negative: method worse); $n$ = common seed pairs;
$p_{\text{Holm}}$ is corrected across all $25$ testable comparisons per
axis (bold: $<0.05$; all bold deltas are negative, i.e.\ worse). PiSSA on
Llama math has one seed against three, so its deltas are reported without
a test. Raw $p$, $t$, and the within-family correction:
\texttt{rq1\_stats/head2head\_corrected.csv}.}
\label{tab:head2head}
\begin{tabular}{l c r c c r c c}
\toprule
 & & \multicolumn{3}{c}{Retention} & \multicolumn{3}{c}{Adaptation} \\
\cmidrule(lr){3-5} \cmidrule(lr){6-8}
Method (cell) & $n$/test & $\Delta$ & $95\%$ CI & $p_{\text{Holm}}$
 & $\Delta$ & $95\%$ CI & $p_{\text{Holm}}$ \\
""" + body + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    open(os.path.join(TABLES, "table_head2head.tex"), "w").write(tex)


if __name__ == "__main__":
    make_tost()
    make_mde()
    make_fragility()
    make_head2head()
    print("wrote table_tost.tex, table_mde.tex, table_fragility.tex, "
          "table_head2head.tex ->", TABLES)
