"""06 — Derive the compact (body) grand table from the frozen
tables/table_grand.tex: Method | Ret | Adapt | F_delta | KL only, all four
model x task blocks kept, laid out as two side-by-side half-tables (Llama
blocks left, Qwen blocks right) inside a table* so the float fits a
page-width band and places early instead of drifting to the back. Purely
mechanical column removal; every number is copied verbatim from the frozen
source (this script must never recompute anything). The full nine-column
version stays in the appendix as tab:grand-full.

Run: /home/guyb/UIOrthoLoRA/.venv/bin/python 06_make_grand_compact.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
TABLES = os.path.abspath(os.path.join(HERE, "..", "..", "tables"))

src = open(os.path.join(TABLES, "table_grand.tex")).read().splitlines()

# ---- parse the frozen table into blocks of 5-column rows -------------------
HEADER = (r"\textbf{Method} & \textbf{Ret} $\uparrow$ & \textbf{Adapt} "
          r"$\uparrow$ & $\dw$ $\downarrow$ & \textbf{KL} $\downarrow$ \\")
blocks = []  # list of (title, [rows])
cur = None
for line in src:
    s = line.strip()
    m = re.match(r"\\multicolumn\{10\}\{c\}\{(.+)\}\s*\\\\", s)
    if m:
        cur = (m.group(1), [])
        blocks.append(cur)
        continue
    if cur is not None and s.endswith(r"\\") and "&" in s:
        cells = [c.strip() for c in s[:-2].split("&")]
        assert len(cells) == 10, f"unexpected column count {len(cells)}: {s}"
        row = " & ".join(cells[:5]) + r" \\"
        # PI decisions (2026-08-04/05): the compact body table carries no
        # marker superscripts at all; both markers stay, defined, in the
        # full appendix table (tab:grand-full).
        row = re.sub(r"\$\^\{(\\ast|\\dagger)\}\$", "", row)
        cur[1].append(row)

assert len(blocks) == 4, f"expected 4 blocks, got {len(blocks)}"


def half_table(pair):
    out = [r"\begin{tabular}{l | cc | cc}", r"\toprule", HEADER]
    for title, rows in pair:
        out += [r"\midrule", r"\multicolumn{5}{c}{%s} \\" % title, r"\midrule"]
        out += rows
    out += [r"\bottomrule", r"\end{tabular}"]
    return out

out = [
    "% AUTO-GENERATED by acl_analysis/rq1_stats/06_make_grand_compact.py:",
    "% column-trimmed copy of the frozen table_grand.tex (numbers verbatim).",
    "% Do not hand-edit numbers.",
    r"\begin{table*}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{3pt}",
    r"% two half-tables side by side (Llama | Qwen) so the float fits one",
    r"% page-width band and places early.",
    r"\begin{minipage}[t]{0.49\textwidth}\centering",
    *half_table(blocks[:2]),
    r"\end{minipage}\hfill",
    r"\begin{minipage}[t]{0.49\textwidth}\centering",
    *half_table(blocks[2:]),
    r"\end{minipage}",
    # Caption is the PI's shortened version (Overleaf d175f60); do not
    # re-expand it.
    r"\caption{Each method at its best adaptation operating point, one block",
    r"per model and task, sorted by retention. Ret, Adapt, $\dw$, and KL are",
    r"mean $\pm$ SD over seeds. The full",
    r"version with the five geometry columns is Table~\ref{tab:grand-full}",
    r"(Appendix~\ref{app:exhibits}).}",
    r"\label{tab:grand}",
    r"\end{table*}",
]

open(os.path.join(TABLES, "table_grand_compact.tex"), "w").write("\n".join(out) + "\n")
print("wrote table_grand_compact.tex")
