#!/usr/bin/env python
"""Rebuild of the lost scratchpad/make_grand_table.py.

Regenerates the frozen 9-column operating-point table
``tables/table_grand.tex`` (label ``tab:grand-full``) from the frozen
analysis stores.  Default mode writes ``tables/table_grand_regen.tex``
and prints a cell-by-cell diff against the frozen file; ``--replace``
overwrites ``tables/table_grand.tex`` itself.

Column provenance
-----------------
Method / Ret / Adapt : adjudication op-point tables
                       (acl_analysis/adjudication/tables/op_points_*.csv);
                       'mean +/- sd' strings reformatted to 1 decimal.
F_delta / KL         : insights/pool.csv rows of the adjudicated cell,
                       columns ``fd`` and ``forgetting_kl``; per-cell
                       mean +/- SD (ddof=1) at 2 decimals.  n=1 prints
                       without +/-; n=0 prints '--'.
SR, e_top, e_bot,    : insights/pool.csv per-cell means of
e_in_top, e_in_bot     ``stable_rank_w``, ``e_top_w``, ``e_bot_w``,
                       ``ein_top_w``, ``ein_bot_w`` (SR 1 decimal,
                       energies 2 decimals).
Base-model rows      : hardcoded retention ceilings 26.0/33.1/44.4/47.9.

Cell resolution: adjudication (family, method, best_lr) -> pool cell,
with family constraints (llama_math -> frm ``_c256`` cells only;
qwen_math -> qwswm cells without ``_ep6_``); residual ambiguity (e.g.
LoRA+wd weight-decay variants, LoRA r16 vs r32) is resolved by matching
the adjudicated adapt mean and fdelta point value.  Blocks keep the 7
canonical methods (PiSSA / CorDA++ / LoRA(r32) rows are not part of the
frozen table) and are sorted by retention descending.  Bold = best per
block (Ret/Adapt max, F_delta/KL min, on unrounded values).  Header,
caption and label text are emitted verbatim from the frozen file.
"""

import argparse
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
WRITING = HERE.parent.parent                      # paper/writing
ACL = WRITING / "acl_analysis"
ADJ = ACL / "adjudication" / "tables"
POOL_CSV = ACL / "insights" / "pool.csv"
FROZEN = WRITING / "tables" / "table_grand.tex"
REGEN = WRITING / "tables" / "table_grand_regen.tex"

# (block key, block title, adjudication csv, pool family, base ceiling)
BLOCKS = [
    ("llama_cs",   r"Llama-2-7B, commonsense",  "op_points_llama_cs.csv",   "lrsw",  "26.0"),
    ("llama_math", r"Llama-2-7B, math",         "op_points_llama_math.csv", "frm",   "33.1"),
    ("qwen_cs",    r"Qwen-2.5-7B, commonsense", "op_points_qwen_cs.csv",    "qwsw",  "44.4"),
    ("qwen_math",  r"Qwen-2.5-7B, math",        "op_points_qwen_math.csv",  "qwswm", "47.9"),
]

# the 7 canonical methods of the grand table; adjudication-only extras
# (PiSSA, CorDA++, LoRA(r32)) are excluded by construction
METHOD_TO_POOL = {
    "LoRA+wd": "lorawd",
    "SC-LoRA": "sclora",
    "LoRA": "lora",
    "LoRA-Null": "lora_null",
    "CLoRA": "clora",
    "MiLoRA": "milora",
    "DoRA": "dora",
}

# footnote markers carried over from Table tab:grand (llama_cs only)
MARKERS = {
    ("llama_cs", "SC-LoRA"): r"$^{\ast}$",
    ("llama_cs", "MiLoRA"): r"$^{\dagger}$",
    ("llama_cs", "DoRA"): r"$^{\dagger}$",
}

HEADER = r"""% AUTO-GENERATED by acl_analysis/rq1_stats/07_make_grand_table.py from the frozen
% adjudication op-point tables + observatory/insights stores (on-pool only).
% Do not hand-edit numbers; rerun the script.
\begin{table*}[t]
\centering
\small
\setlength{\tabcolsep}{9pt}
\resizebox{\textwidth}{!}{%
\begin{tabular}{l | cc | cc | ccccc}
\toprule
\textbf{Method} & \textbf{Ret} $\uparrow$ & \textbf{Adapt} $\uparrow$ & $\dw$ $\downarrow$ & \textbf{KL} $\downarrow$ & \textbf{SR} & $e_{\mathrm{top}}$ & $e_{\mathrm{bot}}$ & $e^{\mathrm{in}}_{\mathrm{top}}$ & $e^{\mathrm{in}}_{\mathrm{bot}}$ \\"""

FOOTER = r"""\bottomrule
\end{tabular}%
}
\caption{Full version of Table~\ref{tab:grand}: each method at its best-adaptation operating point with the geometry columns. Ret, Adapt, $\dw$, and KL are mean $\pm$ SD over seeds (no $\pm$: single-seed coverage; \mbox{--}: no KL coverage); the geometry columns are seed-averaged point values, whose cross-seed SD is below $0.01$; SR values are operating-point stable ranks and differ from the matched-magnitude fingerprints quoted in Section~\ref{sec:results:rq2}. Bold marks the best per block. The two footnote markers of Table~\ref{tab:grand} are defined here. $^{\ast}$SC-LoRA's Llama commonsense cell sits below its family's magnitude curve at its own magnitude; the eval-matched calibration control removes that offset (Section~\ref{sec:results:rq1}), so the offset tracks the calibration corpus rather than the subspace constraint. $^{\dagger}$MiLoRA's and DoRA's low commonsense adaptation means at these cells are answer-format seed collapse, where the model still answers but not in the format the parser extracts; their retention is consistent with the family curve. Metric definitions are in Section~\ref{sec:method:metrics}; operating points follow the adjudication convention of Appendix~\ref{app:pool}.}
\label{tab:grand-full}
\end{table*}"""


def rnd(x, nd):
    """Format with plain IEEE-754 float rounding (Python f-format).

    This is what the original generator used: e.g. the adjudication
    string value 19.15 prints as 19.1 (the binary double is below the
    decimal half) while 87.15 prints as 87.2 — both verified against
    the frozen table.  Decimal half-up would NOT reproduce the frozen
    digits.
    """
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return None
    return f"{float(x):.{nd}f}"


def fmt_pm(mean, sd, nd, n):
    """'m{\\footnotesize$\\pm$s}' cell; no +/- for n==1; '--' for n==0."""
    if n == 0 or mean is None:
        return "--"
    m = rnd(mean, nd)
    if n == 1:
        return m
    return m + r"{\footnotesize$\pm$" + rnd(sd, nd) + "}"


def parse_pm_string(s):
    """'66.79 ± 0.79' -> (66.79, 0.79)."""
    m = re.match(r"\s*([\d.]+)\s*±\s*([\d.]+)", str(s))
    if not m:
        raise ValueError(f"cannot parse mean±sd string: {s!r}")
    return float(m.group(1)), float(m.group(2))


def cell_ok(block_key, cell):
    if block_key == "llama_math":
        return cell.endswith("_c256")
    if block_key == "qwen_math":
        return "_ep6" not in cell
    return True


def resolve_cell(pool, block_key, fam, method, lr, adj_adapt, adj_fdelta):
    """Map an adjudication op point to its pool cell.

    wd-aware: in the frm family plain LoRA was run under the ``lorawd``
    method label with wd=0, so 'LoRA' also admits lorawd cells with
    wd==0, while 'LoRA+wd' requires wd>0.
    """
    pm = METHOD_TO_POOL[method]
    wd = pool["wd"].fillna(0)
    if method == "LoRA":
        meth_ok = (pool["method"] == "lora") | ((pool["method"] == "lorawd") & (wd == 0))
    elif method == "LoRA+wd":
        meth_ok = (pool["method"] == "lorawd") & (wd > 0)
    else:
        meth_ok = pool["method"] == pm
    cand = pool[(pool["fam"] == fam) & meth_ok
                & np.isclose(pool["lr"], lr, rtol=1e-3)]
    cand = cand[cand["cell"].map(lambda c: cell_ok(block_key, c))]
    if cand.empty:
        raise LookupError(f"no pool cell for {fam}/{pm}@lr={lr}")
    # fd is the adjudication's own recorded point value, so weight it
    # heavily; adapt breaks residual ties (pool seed coverage can lag
    # the adjudication's, so adapt means may differ by a few points).
    best, best_score = None, None
    for cell, d in cand.groupby("cell"):
        score = (200 * abs(d["fd"].mean() - adj_fdelta)
                 + abs(d["adapt"].mean() - adj_adapt))
        if best_score is None or score < best_score:
            best, best_score = cell, score
    if best_score > 10:
        raise LookupError(
            f"ambiguous/poor cell match for {fam}/{pm}@lr={lr}: "
            f"best={best} score={best_score:.3f}")
    return best


def agg(series):
    v = series.dropna()
    n = len(v)
    return (v.mean() if n else None,
            v.std(ddof=1) if n > 1 else None,
            n)


def build_rows():
    pool = pd.read_csv(POOL_CSV)
    blocks = []
    for key, title, csv, fam, ceiling in BLOCKS:
        adj = pd.read_csv(ADJ / csv)
        adj = adj[adj["method"].isin(METHOD_TO_POOL)].copy()
        adj["ret_mean"] = adj["ret"].map(lambda s: parse_pm_string(s)[0])
        adj = adj.sort_values("ret_mean", ascending=False)
        rows = []
        for _, r in adj.iterrows():
            am, asd = parse_pm_string(r["adapt"])
            rm, rsd = parse_pm_string(r["ret"])
            cell = resolve_cell(pool, key, fam, r["method"],
                                float(r["best_lr"]), am, float(r["fdelta"]))
            d = pool[pool["cell"] == cell]
            fd_m, fd_s, fd_n = agg(d["fd"])
            kl_m, kl_s, kl_n = agg(d["forgetting_kl"])
            rows.append({
                "method": r["method"], "cell": cell,
                "ret_m": rm, "ret_s": rsd, "adapt_m": am, "adapt_s": asd,
                "n_seeds": int(r["n_seeds"]),
                "fd_m": fd_m, "fd_s": fd_s, "fd_n": fd_n,
                "kl_m": kl_m, "kl_s": kl_s, "kl_n": kl_n,
                "sr": d["stable_rank_w"].mean(),
                "etop": d["e_top_w"].mean(), "ebot": d["e_bot_w"].mean(),
                "eintop": d["ein_top_w"].mean(), "einbot": d["ein_bot_w"].mean(),
            })
        # bold: best per block per column direction, on unrounded values
        def mark(col, best_fn, guard=lambda r: True):
            vals = [(i, r[col]) for i, r in enumerate(rows)
                    if guard(r) and r[col] is not None]
            if vals:
                i = best_fn(vals, key=lambda t: t[1])[0]
                rows[i]["bold_" + col] = True
        mark("ret_m", max)
        mark("adapt_m", max)
        mark("fd_m", min, guard=lambda r: r["fd_n"] > 0)
        mark("kl_m", min, guard=lambda r: r["kl_n"] > 0)
        blocks.append((key, title, ceiling, rows))
    return blocks


def render(blocks):
    lines = [HEADER]
    for key, title, ceiling, rows in blocks:
        lines.append(r"\midrule")
        lines.append(r"\multicolumn{10}{c}{\textbf{%s}} \\" % title)
        lines.append(r"\midrule")
        lines.append(r"\textit{Base model} & \textit{%s} & -- & \textit{0} & "
                     r"\textit{0} & -- & -- & -- & -- & -- \\" % ceiling)
        for r in rows:
            name = r["method"] + MARKERS.get((key, r["method"]), "")
            ret = fmt_pm(r["ret_m"], r["ret_s"], 1, r["n_seeds"])
            adapt = fmt_pm(r["adapt_m"], r["adapt_s"], 1, r["n_seeds"])
            fd = fmt_pm(r["fd_m"], r["fd_s"], 2, r["fd_n"])
            kl = fmt_pm(r["kl_m"], r["kl_s"], 2, r["kl_n"])
            if r.get("bold_ret_m"):
                ret = r"\textbf{%s}" % ret
            if r.get("bold_adapt_m"):
                adapt = r"\textbf{%s}" % adapt
            if r.get("bold_fd_m"):
                fd = r"\textbf{%s}" % fd
            if r.get("bold_kl_m"):
                kl = r"\textbf{%s}" % kl
            cells = [name, ret, adapt, fd, kl, rnd(r["sr"], 1),
                     rnd(r["etop"], 2), rnd(r["ebot"], 2),
                     rnd(r["eintop"], 2), rnd(r["einbot"], 2)]
            lines.append(" & ".join(cells) + r" \\")
    lines.append(FOOTER)
    return "\n".join(lines) + "\n"


def diff_report(generated):
    frozen = FROZEN.read_text()
    gen_body = [l for l in generated.splitlines() if not l.startswith("%")]
    frz_body = [l for l in frozen.splitlines() if not l.startswith("%")]
    n_mismatch = 0
    for i, (g, f) in enumerate(zip(gen_body, frz_body)):
        if g != f:
            n_mismatch += 1
            print(f"MISMATCH body line {i}:")
            print(f"  frozen: {f}")
            print(f"  regen : {g}")
    if len(gen_body) != len(frz_body):
        n_mismatch += 1
        print(f"MISMATCH: body line count regen={len(gen_body)} "
              f"frozen={len(frz_body)}")
    if n_mismatch == 0:
        print("OK: regenerated table matches the frozen table_grand.tex "
              "exactly (all non-comment lines byte-identical).")
    else:
        print(f"FAIL: {n_mismatch} mismatching line(s).")
    return n_mismatch


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--replace", action="store_true",
                    help="overwrite tables/table_grand.tex instead of "
                         "writing tables/table_grand_regen.tex")
    args = ap.parse_args()
    out = render(build_rows())
    target = FROZEN if args.replace else REGEN
    target.write_text(out)
    print(f"wrote {target}")
    sys.exit(1 if diff_report(out) else 0)


if __name__ == "__main__":
    main()
