"""Emit the remaining Llama evaluation queue, deduped against results/.

Single source of truth for what still needs GPU time to finish the Llama half:
6 configurations x 7 arms (A-F), plus the extra G/H arms on config 1. Anything that
already has results/<run>/summary.json is skipped, so this is safe to re-run at any
point and will simply emit less.

Every line: wait for a free GPU -> eval (task + retention + F_delta) -> CE/KL -> evacuate.

Usage:  python build_final_queue.py > jobs/tierA_llama_final.txt
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PY = "/home/kfir/guyb/UIOrthoLoRA/.venv/bin/python"
LLAMA = "meta-llama/Llama-2-7b-hf"
EV = "--adapt_task cs --ret_suite broad --ret_limit 50 --eval_limit 200 --ret_max_gen 512"
GATE = ('until [ "$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits)" '
        '-lt 2000 ]; do sleep 15; done')

# Pareto configurations, in the order results are most useful
CONFIGS = ["tia1_frc_lorawd_wd0p3_lr5e4_s43",
           "tia1_frc_milora_lr3e4_s43",
           "tia1_frc_clora_k1024_lr3e4_s44"]
EXTRA = ["tia1_frc_milora_lr1e3_s43"]          # off-Pareto, high magnitude
CORE_ARMS = ["__rl50", "__k10allablB", "__k10allablC", "__k10allablD",
             "__k10allablE", "__k10allablEp", "__k10allablF1"]
BONUS_ARMS = ["__k10allablG", "__k10allablH"]  # keep-only 2x2, config 1 only


def line(run, adapter_dir, evacuate=True):
    parts = [GATE,
             f"{PY} eval_one_gpu.py --adapter {adapter_dir} --run_name {run} "
             f"--base_model {LLAMA} {EV}",
             f"{PY} forgetting_ce.py --runs {run} --adapters_root /home/kfir/cf_models "
             f"--base_model {LLAMA} --max_length 1024 --max_blocks 0 --batch_size 2"]
    if evacuate:
        parts.append(f"bash evacuate_cell.sh {adapter_dir} /home/kfir/tierA_evac")
    return " && ".join(parts)


def emit():
    out = ["# tierA_llama_final.txt — everything still needed to finish the Llama half.",
           "# Generated by build_final_queue.py; already-completed runs are omitted.",
           "# Order: core A-F per configuration (Pareto configs first), then the extra",
           "# high-magnitude config, then the bonus keep-only arms G/H on config 1."]
    todo = 0
    for group, cfgs, arms in (("core", CONFIGS, CORE_ARMS),
                              ("extra (off-Pareto)", EXTRA, CORE_ARMS),
                              ("bonus keep-only 2x2", CONFIGS[:1], BONUS_ARMS)):
        out.append(f"# --- {group} ---")
        for src in cfgs:
            for arm in arms:
                run = src + arm
                if os.path.exists(os.path.join(HERE, "results", run, "summary.json")):
                    continue
                # arm A is the source adapter re-scored; the others are their own dirs
                adapter = os.path.join("/home/kfir/cf_models", src if arm == "__rl50" else run)
                if not os.path.isdir(adapter):
                    out.append(f"# NOT BUILT YET: {run}")
                    continue
                out.append(line(run, adapter, evacuate=(arm != "__rl50")))
                todo += 1
    out.append(f"# {todo} evaluations pending")
    return "\n".join(out)


if __name__ == "__main__":
    print(emit())
