"""Regenerate tables/table_intruder.tex (Overleaf) with the Llama-2-7B and Qwen2.5-7B blocks.
Cells: retention / task accuracy under the reduced protocol; '--' = not built/infeasible;
'...' = evaluation still running (2026-09-16)."""
import json, os
RES = "results"
def hl(run):
    p = os.path.join(RES, run, "summary.json")
    return json.load(open(p))["headline"] if os.path.exists(p) else None
def intr(run):
    a = json.load(open(os.path.join(RES, "intruder", run + ".json")))["aggregate"]; n = a["n_matrices"]
    return 100 * a["total_intruders_k10_baseAll_t0.5"] / (n * 10), a["mean_energy_share_baseAll_t0.5"]
def cell(h, pending):
    if h is None: return "\\dots" if pending else "--"
    return f"{h['retention_mean']:.2f}/{h['cs_avg']:.2f}"
LLAMA = [("LoRA{+}wd", 32, "tia1_frc_lorawd_wd0p3_lr5e4_s43"), ("CLoRA", 32, "tia1_frc_clora_k1024_lr3e4_s44"),
         ("MiLoRA", 32, "tia1_frc_milora_lr3e4_s43"), ("LoRA", 16, "tia1_frc_lora_r16_lr3e4_s43"),
         ("LoRA-Null", 16, "tia1_frc_loranull_r16_lr5e4_s43")]
QWEN = [("SC-LoRA", 32, "tia1_qwsw_sclora_lr2e5_s43"), ("LoRA", 16, "tia1_qwsw_lora_r16_lr5e5_s43"),
        ("MiLoRA", 32, "tia1_qwsw_milora_lr1e4_s43"), ("LoRA{+}wd", 32, "tia1_qwsw_lorawd_wd0p3_lr1e4_s43"),
        ("CLoRA", 32, "tia1_qwsw_clora_k1024_lr2e4_s43"), ("CLoRA ($3\\times10^{-4}$)", 32, "tia1_qwsw_clora_k1024_lr3e4_s43"),
        ("LoRA-Null", 16, "tia1_qwsw_loranull_r16_lr2e4_s43")]
ARMS = ["__rl50", "__k10allablB", "__k10allablC", "__k10allablD", "__k10allablE"]
# Llama LoRA-Null / LoRA E arms were verified infeasible (not pending); Qwen SC-LoRA E is a copy of A (degenerate)
NOT_BUILT = {("tia1_frc_lora_r16_lr3e4_s43", "__k10allablE"), ("tia1_frc_loranull_r16_lr5e4_s43", "__k10allablE"),
             ("tia1_qwsw_sclora_lr2e5_s43", "__k10allablE")}
def block(rows, arch):
    out = [f"\\multicolumn{{10}}{{l}}{{\\emph{{{arch}}}}} \\\\"]
    for name, r, run in rows:
        frac, en = intr(run); A = hl(run + "__rl50")
        dw = f"{A['fdelta']:.2f}" if A else "\\dots"
        cells = [cell(hl(run + a), (run, a) not in NOT_BUILT) for a in ARMS]
        if run == "tia1_frc_loranull_r16_lr5e4_s43": cells[1] += "$^{\\dagger}$"
        out.append(f"{name} & {r} & {dw} & {frac:.0f}\\% & {en:.2f} & " + " & ".join(cells) + " \\\\")
    return out
base_q = hl("base_qwen25-7b")["retention_mean"]
lines = [
    '% AUTO-GENERATED by make_table_intruder_tex.py (2026-09-16) -- do not hand-edit',
    '\\begin{table*}[t]',
    '\\centering\\footnotesize\\setlength{\\tabcolsep}{3pt}',
    '\\begin{tabular}{l r r r r r r r r r}',
    '\\toprule',
    ' & & & \\multicolumn{2}{c}{Intruder structure} & \\multicolumn{5}{c}{Retention / task accuracy (\\%)} \\\\',
    '\\cmidrule(lr){4-5}\\cmidrule(lr){6-10}',
    ' & & Source & Top-10 & Top-64 & A: source & B: delete & C: uniform & D: B at & E: shrink \\\\',
    "Design & $r$ & $\\dw$ & slots & energy share & unchanged & intruders & shrinkage & A's norm & complement \\\\",
    '\\midrule',
] + block(LLAMA, 'Llama-2-7B (base retention $\\approx 29$)') + ['\\midrule'] + \
    block(QWEN, f"Qwen2.5-7B (base retention {base_q:.2f})") + [
    '\\bottomrule',
    '\\end{tabular}',
    '\\caption{Intruder interventions on commonsense-trained adapters, one seed per configuration.',
    'Each cell gives retention / task accuracy (\\%) on identical examples within a configuration.',
    'B, C and E have matched update Frobenius norms; D matches A (Section~\\ref{sec:method:intruder}).',
    'Occupancy uses the top ten singular directions; energy share uses the top $64$ of the adapted weight.',
    'Qwen base retention uses the same reduced protocol; Llama base retention uses the full battery',
    'and is not directly comparable to these reduced-protocol scores.',
    'For SC-LoRA, only A is reportable; other placeholders are not valid comparisons (Appendix~\\ref{app:intruder}).',
    '--: unavailable; $\\dots$: pending.',
    '$^{\\dagger}$: deletion removes nearly the entire top-ten spectrum.}',
    '\\label{tab:intruder}',
    '\\end{table*}',
]
open("paper/table_intruder.tex", "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
