"""Regenerate tables/table_intruder.tex (Overleaf) with the Llama-2-7B and Qwen2.5-7B blocks.
Final campaign: retention / task accuracy under the reduced protocol.
Missing required summaries are errors; infeasible/degenerate evaluated arms are flagged.
Blue/gray caption edits use the manuscript's existing review macros (ifdiff).
"""
import json, os
RES = "results"
def hl(run):
    p = os.path.join(RES, run, "summary.json")
    return json.load(open(p))["headline"] if os.path.exists(p) else None
def intr(run):
    a = json.load(open(os.path.join(RES, "intruder", run + ".json")))["aggregate"]; n = a["n_matrices"]
    return 100 * a["total_intruders_k10_baseAll_t0.5"] / (n * 10), a["mean_energy_share_baseAll_t0.5"]
def cell(h, unavailable):
    if h is None:
        if unavailable: return "--"
        raise ValueError("Missing required final-campaign summary")
    return f"{h['retention_mean']:.2f}/{h['cs_avg']:.2f}"
LLAMA = [("LoRA{+}wd", 32, "tia1_frc_lorawd_wd0p3_lr5e4_s43"), ("CLoRA", 32, "tia1_frc_clora_k1024_lr3e4_s44"),
         ("MiLoRA", 32, "tia1_frc_milora_lr3e4_s43"), ("LoRA", 16, "tia1_frc_lora_r16_lr3e4_s43"),
         ("LoRA-Null", 16, "tia1_frc_loranull_r16_lr5e4_s43")]
QWEN = [("SC-LoRA", 32, "tia1_qwsw_sclora_lr2e5_s43"), ("LoRA", 16, "tia1_qwsw_lora_r16_lr5e5_s43"),
        ("MiLoRA", 32, "tia1_qwsw_milora_lr1e4_s43"), ("LoRA{+}wd", 32, "tia1_qwsw_lorawd_wd0p3_lr1e4_s43"),
        ("CLoRA", 32, "tia1_qwsw_clora_k1024_lr2e4_s43"), ("CLoRA ($3\\times10^{-4}$)", 32, "tia1_qwsw_clora_k1024_lr3e4_s43"),
        ("LoRA-Null", 16, "tia1_qwsw_loranull_r16_lr2e4_s43")]
ARMS = ["__rl50", "__k10allablB", "__k10allablC", "__k10allablD", "__k10allablE"]
# Retain evaluated diagnostic scores with explicit exclusions, rather than silently
# counting them as matched interventions. Both Qwen E infeasibilities are documented
# in handoff/TIERA_RUN_LOG.md (2026-09-16 entries 08:37 and 08:47).
NOT_EVALUATED = {("tia1_frc_lora_r16_lr3e4_s43", "__k10allablE"),
                 ("tia1_frc_loranull_r16_lr5e4_s43", "__k10allablE")}
INFEASIBLE_E = {"tia1_qwsw_clora_k1024_lr2e4_s43", "tia1_qwsw_loranull_r16_lr2e4_s43"}
def block(rows, arch):
    out = [f"\\multicolumn{{10}}{{l}}{{\\emph{{{arch}}}}} \\\\"]
    for name, r, run in rows:
        frac, en = intr(run); A = hl(run + "__rl50")
        if A is None: raise ValueError(f"Missing final source summary: {run}")
        dw = f"{A['fdelta']:.2f}"
        cells = [cell(hl(run + a), (run, a) in NOT_EVALUATED) for a in ARMS]
        if run == "tia1_frc_loranull_r16_lr5e4_s43": cells[1] += "$^{\\dagger}$"
        if run == "tia1_qwsw_sclora_lr2e5_s43": name += "\\new{$^{\\ddagger}$}"
        if run in INFEASIBLE_E: cells[4] += "\\new{$^{\\S}$}"
        out.append(f"{name} & {r} & {dw} & {frac:.0f}\\% & {en:.2f} & " + " & ".join(cells) + " \\\\")
    return out
base_q = hl("base_qwen25-7b")["retention_mean"]
lines = [
    '% AUTO-GENERATED by make_table_intruder_tex.py (2026-09-17) -- do not hand-edit',
    '\\begin{table*}[t]',
    '\\centering\\footnotesize\\setlength{\\tabcolsep}{2.9pt}',
    '\\begin{tabular}{l r r r r r r r r r}',
    '\\toprule',
    ' & & & \\multicolumn{2}{c}{Intruder structure} & \\multicolumn{5}{c}{Retention / task accuracy (\\%)} \\\\',
    '\\cmidrule(lr){4-5}\\cmidrule(lr){6-10}',
    ' & & Source & Top-10 & Top-64 & A: source & B: delete & C: uniform & D: B at & E: shrink \\\\',
    "Design & $r$ & $\\dw$ & slots & energy share & unchanged & intruders & shrinkage & A's norm & complement \\\\",
    '\\midrule',
] + block(LLAMA, 'Llama-2-7B (base retention $\\approx 29$)') + ['\\midrule'] + \
    block(QWEN, f"Qwen2.5-7B (base retention {base_q:.2f})") + [
    '\\bottomrule',
    '\\end{tabular}',
    '\\caption{Intruder interventions on commonsense-trained adapters, one seed per configuration.',
    'Each cell gives retention / task accuracy (\\%) on identical examples within a configuration.',
    '\\cut{B, C and E have matched update Frobenius norms; D matches A (Section~\\ref{sec:method:intruder}).}',
    '\\new{Except for the flagged exclusions, B, C and E have matched update Frobenius norms; D matches A (Section~\\ref{sec:method:intruder}).}',
    'Occupancy uses the top ten singular directions; energy share uses the top $64$ of the adapted weight.',
    'Qwen base retention uses the same reduced protocol; Llama base retention uses the full battery',
    'and is not directly comparable to these reduced-protocol scores.',
    '\\cut{For SC-LoRA, only A is reportable; other placeholders are not valid comparisons (Appendix~\\ref{app:intruder}).}',
    '\\new{$^{\\ddagger}$: SC-LoRA B--E are numerical-floor diagnostics, excluded from intervention comparisons.}',
    '\\new{$^{\\S}$: E cannot reach B\'s norm and is excluded from matched-norm comparisons (Appendix~\\ref{app:intruder}).}',
    '\\cut{--: unavailable; $\\dots$: pending.} \\new{--: not evaluated because the norm match is infeasible.}',
    '$^{\\dagger}$: deletion removes nearly the entire top-ten spectrum.}',
    '\\label{tab:intruder}',
    '\\end{table*}',
]
open("paper/table_intruder.tex", "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
