"""Regenerate the per-adapter learning-rate-sweep exhibits of
Appendix "The learning-rate sweep, per adapter" (app:lrsweep) from the frozen
run pool. This replaces the lost scratchpad/make_lr_sweep_reports.py; the
lrsw / lrswm / qwsw tables it writes are numerically identical to the committed
2026-07 exhibits (verified by an ordered numeric-token diff at restoration
time).

INTENTIONAL DEPARTURE FROM THE COMMITTED qwswm EXHIBIT (2026-08-04)
------------------------------------------------------------------
The committed Qwen-math exhibit grouped rows by (method, learning rate) only.
On that family, and only there, that convention silently pooled three distinct
configurations into one "LoRA" series and one "LoRA+wd" series:
  * plain LoRA runs on Qwen math as TWO arms, rank 16 and rank 32;
  * six runs (3x qwswm_lora_r32_lr2e4_ep6_*, 3x qwswm_lorawd_wd0p3_lr3e4_ep6_*)
    were trained for six epochs rather than three.
The result was seed counts of n=9 (LoRA at 2e-4) and n=6 (LoRA+wd at 3e-4)
under a caption that calls the column a seed count, which is impossible with
three seeds. This script now:
  * splits plain LoRA on Qwen math into two labelled series, LoRA (r16) and
    LoRA (r32), never pooled;
  * excludes the six six-epoch runs from these exhibits, since a 6-epoch run is
    not a point on a 3-epoch learning-rate sweep. Those runs remain in the
    frozen correlational pool; they enter no sweep or operating-point exhibit.
A hard assertion below now fails if any (family, series, learning rate) group
ever exceeds the five-seed maximum, so a future recurrence surfaces instead of
printing quietly. The other three families are untouched and byte-stable.

No statistics are computed beyond per-(series, learning-rate) means and
sample standard deviations (ddof=1) over seeds, taken directly from pool.csv.
Conventions frozen from the committed exhibits and the app:lrsweep text:
  * one exhibit pair (figure + table) per family: lrsw (Llama CS),
    lrswm (Llama math), qwsw (Qwen CS), qwswm (Qwen math);
  * adaptation = pool column `adapt` (CS-8 for the CS families, GSM8K for
    the math families); retention = `ret` (core) for CS, `bbh` for math;
    update magnitude dw = pool column `fd`;
  * every pool row of the family enters, including the surviving high-rate
    (2e-3 / 5e-3) and quarantined-flagged runs -- the frozen exhibits apply
    no quarantine filter; the two-run MiLoRA+wd transfer arm (lrsw) and the
    non-swept methods (PiSSA, LoRA+wd r16) are not part of the sweep roster
    and are excluded. LoRA-Null is always its own series, never pooled with
    plain LoRA;
  * off-grid single-seed rates (7e-5, 1.5e-4 on Qwen) are their own table
    rows and figure x-positions. NOTE (faithful reproduction of the frozen
    formatting): the LR label truncates the mantissa, so the 1.5e-4 rows
    print as a second "1e-4" row (n=1) directly under the true 1e-4 row;
  * the dotted figure line marks each method's best mean-adaptation rate.

Inputs : ../insights/pool.csv  (hard-asserted to hold exactly 1035 rows)
Outputs: ../../tables/table_lrsweep_{lrsw,lrswm,qwsw,qwswm}.tex
         ../../figures/fig_lrsweep_{...}.{png,pdf}  and identical copies in
         ../figures/ (both figure locations are kept in sync, as committed).
Run    : /home/guyb/UIOrthoLoRA/.venv/bin/python make_lrsweep_exhibits.py
         (add --outdir DIR to divert ALL outputs, e.g. for a dry run)
"""
import argparse
import math
import os
from decimal import Decimal

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
POOL = os.path.join(HERE, "..", "insights", "pool.csv")
TABLES = os.path.abspath(os.path.join(HERE, "..", "..", "tables"))
FIGURES = os.path.abspath(os.path.join(HERE, "..", "..", "figures"))
ACL_FIGURES = os.path.abspath(os.path.join(HERE, "..", "figures"))

HDR = ("% AUTO-GENERATED by acl_analysis/lrsweep/make_lrsweep_exhibits.py "
       "from insights/pool.csv -- do not hand-edit.\n")

DISPLAY = {"lorawd": "LoRA+wd", "lora": "LoRA", "dora": "DoRA",
           "milora": "MiLoRA", "sclora": "SC-LoRA",
           "lora_null": "LoRA-Null", "clora": "CLoRA",
           "lora_r32": "LoRA (r32)"}

# Series that must not be pooled under a bare method name. Keyed by
# (family, series) so the three byte-stable families keep their exact labels.
SERIES_DISPLAY = {("qwswm", "lora"): "LoRA (r16)"}

# Runs excluded from the sweep exhibits (see the module docstring): a 6-epoch
# run is not a point on a 3-epoch learning-rate sweep.
EXCLUDE_SUBSTR = "_ep6_"


def add_series(pool):
    """Series label per run: the method, except that plain LoRA on Qwen math
    splits by rank (two distinct arms were trained there)."""
    s = pool.method.copy()
    split = (pool.fam == "qwswm") & (pool.method == "lora") & (pool["rank"] == 32)
    s = s.where(~split, "lora_r32")
    return pool.assign(series=s)

# figstyle.PALETTE colours (titles follow the method; blue/red inside a panel
# are the fixed adaptation/retention roles, not method colours)
METHOD_C = {"lorawd": "#1baf7a", "lora": "#2a78d6", "dora": "#e87ba4",
            "milora": "#eda100", "sclora": "#e34948",
            "lora_null": "#008300", "clora": "#4a3aa7",
            "lora_r32": "#0b4c8c"}
ADAPT_C = "#2a78d6"
RET_C = "#e34948"
GRID_C = "#e1e0d9"
VLINE_C = "#444444"

# family -> (model+task caption stem, adaptation column label, retention
# pool column, retention column label, retention legend label,
# [left minipage methods], [right minipage methods])
FAMS = {
    "lrsw": ("Llama-2-7B commonsense", "CS-8", "ret",
             r"Ret $\uparrow$", "Core retention",
             ["lorawd", "lora", "dora", "milora"],
             ["sclora", "lora_null", "clora"]),
    "lrswm": ("Llama-2-7B math", "GSM8K", "bbh",
              r"BBH $\uparrow$", "BBH retention",
              ["lorawd", "lora", "dora"],
              ["milora", "sclora", "clora"]),
    "qwsw": ("Qwen2.5-7B commonsense", "CS-8", "ret",
             r"Ret $\uparrow$", "Core retention",
             ["lorawd", "lora", "dora", "milora"],
             ["sclora", "lora_null", "clora"]),
    "qwswm": ("Qwen2.5-7B math", "GSM8K", "bbh",
              r"BBH $\uparrow$", "BBH retention",
              ["lorawd", "lora", "lora_r32", "dora"],
              ["milora", "sclora", "lora_null", "clora"]),
}
RET_CAPTION = {"ret": "core: BBH, MMLU-Pro", "bbh": "BBH"}


def lr_label(lr):
    """Frozen-exhibit LR label: truncated mantissa, e.g. 0.00007 -> '7e-5'.
    Faithfully reproduces the committed quirk that 1.5e-4 prints as '1e-4'."""
    exp = math.floor(math.log10(lr))
    mant = int(lr / 10 ** exp + 1e-9)
    return f"{mant}e{exp}"


def cell_stats(sub, ret_col):
    """Per-(method, lr) n / mean / sample-SD rows, lr ascending."""
    g = (sub.groupby("lr")
            .agg(n=("adapt", "size"),
                 adapt=("adapt", "mean"), adapt_sd=("adapt", "std"),
                 ret=(ret_col, "mean"), ret_sd=(ret_col, "std"),
                 fd=("fd", "mean"), fd_sd=("fd", "std"))
            .reset_index().sort_values("lr"))
    return g


# ---------------------------------------------------------------------------
# One cell of the frozen exhibits cannot be derived from pool.csv: the Llama
# math DoRA 3e-4 adaptation mean. Its three pool values (46.93, 45.26, 47.16)
# average to EXACTLY 46.45, and the committed table prints 46.4, while the
# committed Llama math LoRA 1e-3 cell is the mirror-image tie (exactly 41.95,
# printed 42.0). No single summation order or rounding rule on the 2-decimal
# pool values resolves both ties in those opposite directions (verified
# exhaustively at restoration time); the frozen digits reflect the original
# scratchpad script's full-precision inputs, which pool.csv rounds away. We
# therefore pin that one cell to its committed rendering. The pin is applied
# ONLY when the exact pool mean still equals the recorded tie value, so any
# future data change surfaces instead of being masked.
TIE_PIN = {("lrswm", "dora", "3e-4", "adapt", 1): ("46.45", "46.4")}


def dec_mean(vals, dec, pin_key=None):
    """Cell mean formatted as in the frozen exhibits: the exact decimal mean
    of the CSV values is taken to its nearest float64 and printed with
    Python's formatter. Several cell means land exactly on a rounding tie
    (41.95, 37.95, 85.55, 77.25, 0.105, 0.085); float summation drifts off
    the correctly-rounded double there and flips the last printed digit
    against the committed tables. One residual tie is pinned via TIE_PIN
    (see above). No statistics beyond the mean are involved."""
    m = sum(Decimal(str(v)) for v in vals) / len(vals)
    if pin_key in TIE_PIN:
        exact, rendered = TIE_PIN[pin_key]
        if m == Decimal(exact):
            return rendered
    return f"{float(m):.{dec}f}"


def fmt_pm(vals, sd, dec, pin_key=None):
    if pd.isna(sd):
        return dec_mean(vals, dec, pin_key)
    return (dec_mean(vals, dec, pin_key)
            + r"{\footnotesize$\pm$" + f"{sd:.{dec}f}" + "}")


def series_label(fam, series):
    return SERIES_DISPLAY.get((fam, series), DISPLAY[series])


def method_block(fam, pool_fam, method, ret_col):
    rows = [r"\multicolumn{5}{l}{\textbf{%s}} \\" % series_label(fam, method)]
    sub = pool_fam[pool_fam.series == method]
    g = cell_stats(sub, ret_col)
    for _, x in g.iterrows():
        cell = sub[sub.lr == x.lr]
        lab = lr_label(x.lr)
        rows.append(
            f"{lab} & {int(x.n)} & "
            f"{fmt_pm(cell.adapt, x.adapt_sd, 1, (fam, method, lab, 'adapt', 1))} & "
            f"{fmt_pm(cell[ret_col], x.ret_sd, 1, (fam, method, lab, ret_col, 1))} & "
            f"{fmt_pm(cell.fd, x.fd_sd, 2, (fam, method, lab, 'fd', 2))} \\\\")
    return rows


def minipage(fam, pool_fam, methods, adapt_label, ret_col, ret_hdr):
    lines = [r"\begin{minipage}[t]{0.49\textwidth}\centering",
             r"\footnotesize",
             r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{l r c c c}",
             r"\toprule",
             (r"LR & $n$ & %s $\uparrow$ & %s & $\dw\downarrow$ \\"
              % (adapt_label, ret_hdr)),
             r"\midrule"]
    for i, m in enumerate(methods):
        if i:
            lines.append(r"\midrule")
        lines += method_block(fam, pool_fam, m, ret_col)
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{minipage}"]
    return lines


def make_table(pool, fam, outdir):
    stem, adapt_label, ret_col, ret_hdr, _, left, right = FAMS[fam]
    pf = pool[pool.fam == fam]
    lines = [HDR.rstrip("\n"), r"\begin{table*}[t]", r"\centering"]
    lines += minipage(fam, pf, left, adapt_label, ret_col, ret_hdr)
    lines[-1] += r"\hfill"
    lines += minipage(fam, pf, right, adapt_label, ret_col, ret_hdr)
    caption = (r"\caption{Learning-rate sweep, %s. Every method at each swept "
               r"learning rate: seed count $n$, adaptation (%s), retention "
               r"(%s), and update magnitude $\dw$ (mean $\pm$ SD over seeds; "
               r"no $\pm$ = single seed). Individual seeds are the dots in "
               r"Figure~\ref{fig:lrsweep-%s}.}"
               % (stem, adapt_label, RET_CAPTION[ret_col], fam))
    lines += [caption, r"\label{tab:lrsweep-%s}" % fam, r"\end{table*}"]
    path = os.path.join(outdir, f"table_lrsweep_{fam}.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def panel(ax, sub, g, ret_col, method, fam):
    ax2 = ax.twinx()
    ax.set_zorder(ax2.get_zorder() + 1)
    ax.patch.set_visible(False)
    for a in (ax, ax2):
        a.set_xscale("log")
    ax.grid(True, axis="x", which="both", color=GRID_C, lw=0.8, zorder=0)
    ax.grid(False, axis="y")
    ax2.grid(False)
    # individual seeds
    ax.scatter(sub.lr, sub.adapt, s=14, color=ADAPT_C, alpha=0.35,
               marker="o", linewidths=0, zorder=2)
    ax2.scatter(sub.lr, sub[ret_col], s=14, color=RET_C, alpha=0.35,
                marker="s", linewidths=0, zorder=2)
    # mean lines + SD bands
    sd_a = g.adapt_sd.fillna(0.0)
    sd_r = g.ret_sd.fillna(0.0)
    ax.fill_between(g.lr, g.adapt - sd_a, g.adapt + sd_a,
                    color=ADAPT_C, alpha=0.13, lw=0, zorder=1)
    ax2.fill_between(g.lr, g.ret - sd_r, g.ret + sd_r,
                     color=RET_C, alpha=0.13, lw=0, zorder=1)
    ax.plot(g.lr, g.adapt, color=ADAPT_C, marker="o", ms=5, lw=1.8, zorder=3)
    ax2.plot(g.lr, g.ret, color=RET_C, marker="s", ms=5, lw=1.8, zorder=3)
    # best-adaptation rate
    best_lr = g.loc[g.adapt.idxmax(), "lr"]
    ax.axvline(best_lr, color=VLINE_C, ls=":", lw=1.1, zorder=2)
    ax.set_title(series_label(fam, method), color=METHOD_C[method],
                 fontweight="bold", fontsize=13)
    ax.tick_params(axis="y", labelcolor=ADAPT_C, labelsize=9)
    ax2.tick_params(axis="y", labelcolor=RET_C, labelsize=9)
    ax.tick_params(axis="x", labelsize=9)


def make_figure(pool, fam, outdirs):
    _, adapt_label, ret_col, _, ret_legend, left, right = FAMS[fam]
    methods = left + right
    pf = pool[pool.fam == fam]
    fig, axes = plt.subplots(2, 4, figsize=(12.6, 5.3))
    axes = axes.ravel()
    for ax in axes[len(methods):]:
        ax.set_visible(False)
    for ax, m in zip(axes, methods):
        sub = pf[pf.series == m]
        panel(ax, sub, cell_stats(sub, ret_col), ret_col, m, fam)
    handles = [
        Line2D([], [], color=ADAPT_C, marker="o", ms=6, lw=1.8,
               label=f"Adaptation ({adapt_label})"),
        Line2D([], [], color=RET_C, marker="s", ms=6, lw=1.8,
               label=ret_legend),
        Line2D([], [], color=VLINE_C, ls=":", lw=1.2, label="best-adapt LR"),
    ]
    fig.legend(handles=handles, loc="upper center", ncol=3, frameon=False,
               bbox_to_anchor=(0.5, 1.02), fontsize=10.5)
    fig.supxlabel("learning rate (log scale)", fontsize=11)
    fig.tight_layout(rect=(0, 0.02, 1, 0.96))
    paths = []
    for d in outdirs:
        os.makedirs(d, exist_ok=True)
        for ext in ("png", "pdf"):
            p = os.path.join(d, f"fig_lrsweep_{fam}.{ext}")
            fig.savefig(p, dpi=150, bbox_inches="tight")
            paths.append(p)
    plt.close(fig)
    return paths


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=None,
                    help="divert all outputs to this directory (dry run)")
    args = ap.parse_args()

    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans", "Arial", "Helvetica"],
        "axes.edgecolor": "#c3c2b7",
        "axes.linewidth": 1.0,
        "xtick.color": "#52514e",
        "ytick.color": "#52514e",
        "figure.facecolor": "white",
        "savefig.facecolor": "white",
    })

    pool = pd.read_csv(POOL)
    assert len(pool) == 1035, (
        f"pool.csv must hold exactly 1035 rows, got {len(pool)}")

    dropped = pool.rn.str.contains(EXCLUDE_SUBSTR)
    assert dropped.sum() == 6, (
        f"expected exactly 6 six-epoch runs to exclude, got {dropped.sum()}")
    pool = add_series(pool[~dropped].copy())

    # No (family, series, learning rate) group may exceed the five-seed
    # maximum; a larger count means two configurations were pooled.
    counts = (pool[pool.fam.isin(FAMS)]
              .groupby(["fam", "series", "lr"]).size())
    assert counts.max() <= 5, (
        "a sweep series pools more runs than there are seeds:\n"
        + str(counts[counts > 5]))

    tab_dir = args.outdir or TABLES
    fig_dirs = [args.outdir] if args.outdir else [FIGURES, ACL_FIGURES]
    os.makedirs(tab_dir, exist_ok=True)

    written = []
    for fam in FAMS:
        written.append(make_table(pool, fam, tab_dir))
        written += make_figure(pool, fam, fig_dirs)
    for p in written:
        print("wrote", p)


if __name__ == "__main__":
    main()
